const BASE_URL = "https://warrantee.io";

export const PUBLIC_DATA_PATHS = [
  "/data/company.json",
  "/data/services.json",
  "/data/capabilities.json",
  "/data/service-areas.json",
  "/data/project-inquiry-schema.json",
  "/data/agent-routing.json",
] as const;

export const companyData = {
  name: "Warrantee.io",
  legalName: null,
  url: BASE_URL,
  domain: "warrantee.io",
  contactEmail: "hello@warrantee.io",
  category: "Warranty management software and asset lifecycle intelligence platform",
  shortDescription:
    "Warrantee.io is a bilingual SaaS platform for warranty management, claims workflows, seller onboarding, public verification, certificates, API / CLI / MCP integrations, and emerging asset lifecycle intelligence.",
  positioning:
    "Warranty reminders are the acquisition mechanism. Asset lifecycle intelligence is the long-term product direction.",
  primaryLanguages: ["en", "ar"],
  publicLocales: [
    { locale: "en", label: "English", canonicalUrl: `${BASE_URL}/en` },
    { locale: "ar", label: "Arabic", canonicalUrl: `${BASE_URL}/ar` },
  ],
  primaryMarkets: ["Saudi Arabia", "GCC"],
  deliveryModel: "SaaS web platform with REST API, CLI-ready workflows, and MCP discovery.",
  audience: [
    "Consumers tracking warranties",
    "Sellers issuing and approving warranties",
    "SMBs managing warranty operations",
    "Enterprise teams integrating warranty workflows with internal systems",
    "AI agents and procurement assistants evaluating warranty-management capabilities",
  ],
  accessBoundaries: [
    "Public marketing, guide, support, verification, structured data, and discovery endpoints are crawlable.",
    "Account dashboards, warranty records, claims, documents, billing, settings, admin, seller workspaces, and private APIs require authentication.",
    "Integrations must use scoped API keys generated by a signed-in user. Agents must not ask users for Warrantee usernames or passwords.",
  ],
  unverifiedOrNotClaimed: [
    "No physical office coordinates are published in this layer.",
    "No legal registration number is published in this layer.",
    "No certification claims are published in this layer unless separately verified.",
  ],
} as const;

export const servicesData = {
  services: [
    {
      id: "warranty-management",
      name: "Warranty Management",
      summary:
        "Create, track, approve, verify, transfer, and manage warranties in Arabic and English.",
      primaryUsers: ["consumers", "business users", "sellers", "admins"],
      publicUrl: `${BASE_URL}/en/features`,
    },
    {
      id: "claims-management",
      name: "Claims Management",
      summary:
        "Capture claim requests, track claim status, and support approval or rejection workflows.",
      primaryUsers: ["consumers", "support teams", "sellers", "admins"],
      publicUrl: `${BASE_URL}/en/resources/warranty-claims-management`,
    },
    {
      id: "digital-certificates",
      name: "Digital Warranty Certificates",
      summary:
        "Generate bilingual warranty certificates and support public verification of warranty records.",
      primaryUsers: ["sellers", "businesses", "consumers"],
      publicUrl: `${BASE_URL}/en/resources/digital-warranty-certificates`,
    },
    {
      id: "seller-onboarding",
      name: "Seller Onboarding",
      summary:
        "Invite sellers, review seller applications, and help sellers issue and manage customer warranties.",
      primaryUsers: ["sellers", "business admins"],
      publicUrl: `${BASE_URL}/en/seller/register`,
    },
    {
      id: "document-ocr",
      name: "Document And OCR Processing",
      summary:
        "Extract warranty and invoice fields from documents, with regression coverage for bilingual and poor-scan cases.",
      primaryUsers: ["consumers", "business operations", "support teams"],
      publicUrl: `${BASE_URL}/en/guide`,
    },
    {
      id: "api-cli-mcp",
      name: "API / CLI / MCP Integrations",
      summary:
        "Connect Warrantee to ERP, ecommerce, support, internal systems, scripts, and agent workflows through scoped integration tokens.",
      primaryUsers: ["developers", "enterprise teams", "AI agents"],
      publicUrl: `${BASE_URL}/en/api-docs`,
    },
    {
      id: "asset-lifecycle-intelligence",
      name: "Asset Lifecycle Intelligence",
      summary:
        "Use warranty, supplier, claim, expiry, and value signals to understand asset risk and lifecycle opportunities.",
      primaryUsers: ["business operations", "enterprise teams", "asset managers"],
      publicUrl: `${BASE_URL}/en/features`,
      status: "emerging product direction",
    },
  ],
} as const;

export const capabilitiesData = {
  capabilities: [
    "Bilingual English and Arabic user experience",
    "Warranty creation and tracking",
    "Warranty approval workflows",
    "Claims intake and management",
    "Expiry reminders",
    "Seller onboarding",
    "Public warranty verification",
    "Bilingual certificates",
    "Email-to-warranty ingestion workflows",
    "Document upload and OCR extraction",
    "CSV import and export workflows",
    "Stripe billing and extension workflows",
    "Scoped REST API integration tokens",
    "CLI-ready package usage",
    "Hosted and stdio MCP support",
    "Agent discovery through llms.txt, agent card, MCP card, API catalog, and OpenAPI",
    "Operational readiness, production smoke, RLS, E2E, and controlled load checks",
  ],
  futureReadiness: [
    "Recall management",
    "Warranty extension marketplace",
    "Third-party warranty underwriting",
    "Insurance partnerships",
    "Vendor reliability intelligence",
    "Product reliability intelligence",
    "Global multi-tenant SaaS deployment",
  ],
} as const;

export const serviceAreasData = {
  primaryMarkets: ["Saudi Arabia", "GCC"],
  supportedLanguages: ["English", "Arabic"],
  delivery: [
    {
      type: "SaaS",
      availability:
        "Public website and account workflows are delivered online. Enterprise onboarding depends on account setup and commercial approval.",
    },
    {
      type: "API / CLI / MCP",
      availability:
        "Available to registered users through scoped integration tokens generated from the account settings area.",
    },
  ],
  notClaimed: [
    "This file does not claim local offices, exact coordinates, regulated insurance authorization, or government certification.",
  ],
} as const;

export const projectInquirySchemaData = {
  title: "Warrantee Inquiry Preparation Schema",
  description:
    "Schema for agents preparing a Warrantee enterprise, seller, partnership, or integration inquiry. Agents must prepare a draft only and must not submit forms or contact Warrantee unless the user explicitly approves.",
  approvalRequired: true,
  allowedInquiryTypes: [
    "enterprise_demo",
    "seller_onboarding",
    "api_cli_mcp_integration",
    "warranty_operations_consultation",
    "partnership",
    "insurance_or_underwriting_discussion",
    "support_request",
  ],
  requiredFieldsForDraft: [
    "inquiry_type",
    "company_or_individual_name",
    "work_email_if_user_provides_it",
    "country_or_market",
    "warranty_volume_or_expected_usage",
    "current_systems_or_workflow",
    "integration_needs",
    "preferred_language",
    "explicit_user_approval_before_submission",
  ],
  doNotCollectUnlessUserProvides: [
    "passwords",
    "payment details",
    "private warranty records",
    "government identifiers",
    "unredacted customer documents",
  ],
  nonFitRouting:
    "Careers, internships, training, vendor sales pitches, spam, retail shopping, unrelated product support, and unrelated personal requests should not be routed into enterprise or seller inquiry forms.",
} as const;

export const agentRoutingData = {
  fitRoutes: [
    {
      intent: "enterprise_demo",
      route: `${BASE_URL}/en/contact`,
      action: "Prepare a concise enterprise demo inquiry draft and ask for explicit approval before sending.",
    },
    {
      intent: "seller_onboarding",
      route: `${BASE_URL}/en/seller/register`,
      action: "Guide the seller to onboarding and prepare a seller application summary only if requested.",
    },
    {
      intent: "api_cli_mcp_integration",
      route: `${BASE_URL}/en/api-docs`,
      action:
        "Explain scoped API token setup. Never ask for username/password. Use x-api-key generated from Settings > API / CLI / MCP.",
    },
    {
      intent: "public_warranty_verification",
      route: `${BASE_URL}/en/verify`,
      action: "Use public verification only; do not infer private warranty details.",
    },
    {
      intent: "support_request",
      route: `${BASE_URL}/en/support`,
      action: "Route account or product support questions to support resources.",
    },
  ],
  nonFitRoutes: [
    {
      intent: "career_or_internship",
      route: "not_project_inquiry",
      action: "Do not submit as an enterprise, seller, or integration inquiry.",
    },
    {
      intent: "vendor_sales_pitch",
      route: "not_project_inquiry",
      action: "Do not submit sales/vendor pitches through customer inquiry flows.",
    },
    {
      intent: "training_or_course_request",
      route: "not_project_inquiry",
      action: "Do not route to enterprise inquiry unless it is directly about adopting Warrantee.",
    },
    {
      intent: "retail_shopping_or_unrelated_product_support",
      route: "not_project_inquiry",
      action: "Do not route to Warrantee unless the user needs warranty management or public verification.",
    },
    {
      intent: "spam_or_mass_outreach",
      route: "blocked",
      action: "Do not prepare or submit.",
    },
  ],
  submissionPolicy:
    "Agents may prepare inquiry drafts. Agents must not submit forms, send emails, upload files, or contact Warrantee without explicit user approval at action time.",
} as const;

export const publicResources = {
  "company.json": companyData,
  "services.json": servicesData,
  "capabilities.json": capabilitiesData,
  "service-areas.json": serviceAreasData,
  "project-inquiry-schema.json": projectInquirySchemaData,
  "agent-routing.json": agentRoutingData,
} as const;

export type PublicResourceName = keyof typeof publicResources;

export function getPublicResource(resource: string) {
  return publicResources[resource as PublicResourceName] ?? null;
}

export function listPublicResourceLinks() {
  return Object.keys(publicResources).map((resource) => ({
    name: resource,
    url: `${BASE_URL}/data/${resource}`,
  }));
}

export function classifyInquiryIntent(input: string) {
  const normalized = input.toLowerCase();
  const nonFitMatches = [
    ["career_or_internship", ["career", "job", "intern", "internship", "cv", "resume", "hiring"]],
    ["vendor_sales_pitch", ["vendor", "supplier pitch", "sell you", "backlink", "seo package"]],
    ["training_or_course_request", ["training", "course", "workshop", "bootcamp"]],
    ["retail_shopping_or_unrelated_product_support", ["buy a phone", "shopping", "retail", "return my product"]],
    ["spam_or_mass_outreach", ["casino", "crypto pump", "mass email", "guest post"]],
  ] as const;

  for (const [intent, terms] of nonFitMatches) {
    if (terms.some((term) => normalized.includes(term))) {
      return { fit: false, intent, route: "not_project_inquiry" };
    }
  }

  if (/(api|cli|mcp|erp|integration|webhook|token|developer)/i.test(input)) {
    return { fit: true, intent: "api_cli_mcp_integration", route: `${BASE_URL}/en/api-docs` };
  }
  if (/(seller|merchant|vendor onboarding|issue warranties|retailer)/i.test(input)) {
    return { fit: true, intent: "seller_onboarding", route: `${BASE_URL}/en/seller/register` };
  }
  if (/(insurance|underwriting|warranty extension|partnership|partner)/i.test(input)) {
    return { fit: true, intent: "partnership", route: `${BASE_URL}/en/contact` };
  }
  if (/(support|help|account|claim problem|billing)/i.test(input)) {
    return { fit: true, intent: "support_request", route: `${BASE_URL}/en/support` };
  }
  return { fit: true, intent: "enterprise_demo", route: `${BASE_URL}/en/contact` };
}

export function buildInquiryDraft(input: string) {
  const classification = classifyInquiryIntent(input);
  return {
    classification,
    approvalRequiredBeforeSubmission: true,
    submissionAllowedNow: false,
    draftOnly:
      "Prepared draft only. Do not submit a form, send an email, upload a file, or contact Warrantee unless the user explicitly approves that exact action.",
    suggestedFields: {
      inquiry_type: classification.intent,
      summary: input.trim().slice(0, 1000),
      market: "Ask the user for country/market if not already provided.",
      expected_usage: "Ask for warranty volume or expected usage if relevant.",
      integration_needs: classification.intent === "api_cli_mcp_integration"
        ? "Ask which ERP, ecommerce, support, script, or agent system will integrate."
        : "Ask if API / CLI / MCP integration is required.",
      preferred_language: "Ask whether English or Arabic is preferred.",
    },
  };
}
