import { PUBLIC_DATA_PATHS } from "@/lib/agent-public-data";

const BASE_URL = "https://warrantee.io";

export function buildPublicOpenApi() {
  const dataPaths = Object.fromEntries(
    PUBLIC_DATA_PATHS.map((path) => [
      path,
      {
        get: {
          summary: `Read ${path}`,
          description: "Public read-only structured data for search engines, LLMs, procurement agents, and AI assistants.",
          responses: {
            "200": { description: "Public structured data returned" },
          },
        },
      },
    ]),
  );

  return {
    openapi: "3.1.0",
    info: {
      title: "Warrantee Public Discovery And Integration API",
      version: "1.1.0",
      description:
        "Public OpenAPI description for Warrantee structured data, agent discovery, warranty verification, API / CLI / MCP integration guidance, and authenticated warranty-management APIs.",
    },
    servers: [{ url: BASE_URL }],
    paths: {
      ...dataPaths,
      "/llms.txt": {
        get: { summary: "Read LLM summary", responses: { "200": { description: "LLM summary returned" } } },
      },
      "/llms-full.txt": {
        get: { summary: "Read full LLM brief", responses: { "200": { description: "Full LLM brief returned" } } },
      },
      "/auth.md": {
        get: { summary: "Read integration auth guide", responses: { "200": { description: "Auth guide returned" } } },
      },
      "/.well-known/agent-card.json": {
        get: { summary: "Read agent discovery card", responses: { "200": { description: "Agent card returned" } } },
      },
      "/.well-known/api-catalog": {
        get: { summary: "Read API catalog linkset", responses: { "200": { description: "API catalog returned" } } },
      },
      "/.well-known/mcp.json": {
        get: { summary: "Read MCP server card", responses: { "200": { description: "MCP server card returned" } } },
      },
      "/.well-known/mcp/server-card.json": {
        get: { summary: "Read MCP server card alias", responses: { "200": { description: "MCP server card returned" } } },
      },
      "/.well-known/mcp/server-cards.json": {
        get: { summary: "Read MCP server card collection", responses: { "200": { description: "MCP server cards returned" } } },
      },
      "/api/mcp": {
        get: {
          summary: "Describe hosted MCP endpoint",
          responses: { "200": { description: "Hosted MCP transport metadata returned" } },
        },
        post: {
          summary: "Call hosted MCP JSON-RPC endpoint",
          description:
            "Public read-only discovery tools do not require account credentials. Private warranty, claim, document, seller, and account tools require a scoped x-api-key generated by a signed-in Warrantee user. Agents must not ask for usernames or passwords.",
          responses: {
            "200": { description: "MCP JSON-RPC response returned" },
            "429": { description: "Rate limit exceeded" },
          },
        },
      },
      "/api/v1/warranties/verify": {
        get: {
          summary: "Verify warranty",
          description: "Public warranty verification. Does not expose private account data.",
          responses: { "200": { description: "Verification result returned" } },
        },
      },
      "/api/v1/warranties": {
        get: {
          summary: "List authenticated warranties",
          security: [{ ApiKeyAuth: [] }, { BearerAuth: [] }],
          responses: { "200": { description: "Visible warranties returned" } },
        },
        post: {
          summary: "Create authenticated warranty",
          security: [{ ApiKeyAuth: [] }, { BearerAuth: [] }],
          responses: { "201": { description: "Warranty created" } },
        },
      },
      "/api/v1/intelligence": {
        get: {
          summary: "Read authenticated asset lifecycle intelligence",
          description:
            "Returns portfolio-level warranty, claim, supplier, expiry, data-quality, and next-action signals for the authenticated account. Requires a scoped integration token or bearer token with warranties:read access.",
          security: [{ ApiKeyAuth: [] }, { BearerAuth: [] }],
          parameters: [
            {
              name: "limit",
              in: "query",
              required: false,
              schema: { type: "integer", minimum: 1, maximum: 10000, default: 5000 },
              description: "Maximum warranties included in the intelligence calculation.",
            },
          ],
          responses: {
            "200": { description: "Asset intelligence summary returned" },
            "401": { description: "Missing or invalid authentication" },
            "403": { description: "Token lacks required scope" },
            "429": { description: "Rate limit exceeded" },
          },
        },
      },
      "/api/claims": {
        post: {
          summary: "Submit claim",
          security: [{ BearerAuth: [] }],
          responses: { "201": { description: "Claim created" } },
        },
      },
    },
    components: {
      securitySchemes: {
        ApiKeyAuth: {
          type: "apiKey",
          in: "header",
          name: "x-api-key",
          description:
            "Scoped integration token generated from a signed-in Warrantee account. Do not use a username or password.",
        },
        BearerAuth: {
          type: "http",
          scheme: "bearer",
          description: "Supabase-backed session or service token for approved authenticated workflows.",
        },
      },
    },
    "x-agent-policy": {
      approvalRequiredBeforeSubmission: true,
      nonFitRouting:
        "Careers, vendors, internships, training, spam, retail shopping, and unrelated requests should not be routed into Warrantee enterprise or seller inquiry flows.",
    },
  };
}
